/* ============================================================
 * MB Architects — Project Manifest
 * 52 portfolio projects backed by image folders in portfolio/
 * Schema: { slug, num, title, subtitle?, location, tags[],
 *           typology, year, role, status, cost, costNum?, client?,
 *           description, cover, gallery[], photos? }
 *
 * cover     = real photo hero (cover-image.jpg) or PDF cover page fallback
 * gallery[] = PDF cover page as Plate 01 + drawing plates 02..N
 * photos[]  = slideshow array (≥3 real photos only)
 * ============================================================ */
window.MB_PROJECTS = (function () {
  const covPhoto = (s) => `images/portfolio/${s}/cover-image.jpg`;
  const cov      = (s) => `images/portfolio/${s}/cover.jpg`;

  // Gallery: cover.jpg as Plate 01, then PDF plates 01..n as Plate 02..n+1
  const galFull = (s, n) => {
    const out = [{ src: `images/portfolio/${s}/cover.jpg`, label: "Plate 01" }];
    for (let i = 1; i <= n; i++) {
      const k = String(i).padStart(2, "0");
      out.push({ src: `images/portfolio/${s}/${k}.jpg`, label: `Plate ${String(i + 1).padStart(2, "0")}` });
    }
    return out;
  };

  // Photos array for slideshow
  const phots = (s, n) => Array.from({ length: n }, (_, i) =>
    `images/portfolio/${s}/photo-${String(i + 1).padStart(2, "0")}.jpg`
  );

  // Slugs without backing portfolio/<slug>/ folder — hidden from listing & detail.
  const UNPUBLISHED = new Set([
    "private-client-villa", "noun-villa-staff", "veritas-branch-network",
    "private-client-anthony", "private-client-ikoyi", "private-client-suburban",
    "bank-branch-rollout", "branded-banking-prototype", "regional-office-development",
    "lekki-villa-cluster", "abuja-villa-2025", "ibadan-villa-2025",
    "noun-mccarthy-lagos", "urban-housing-2025", "residential-urban-development-2025",
    "infill-housing", "mb-architects-hq", "research-eko-atlantic", "research-ibeju-lekki"
  ]);

  const _ALL = [
    {
      slug: "bourdillon",
      num: "05",
      featured: true,
      title: "Bourdillon",
      location: "Ikoyi, Lagos, Nigeria",
      tags: ["Urban", "Housing", "2025"],
      typology: "Urban Housing",
      year: 2025,
      role: "Architect Only",
      status: "Concept Stage",
      cost: "$25M",
      costNum: 25_000_000,
      client: "MB Architects / Kodai Construction",
      description: "A luxury residential development comprising premium 2-, 3-, and 4-bedroom apartments and penthouses, designed to redefine high-rise living in Ikoyi with modern aesthetics and smart home integration.",
      cover: covPhoto("bourdillon"),
      gallery: galFull("bourdillon", 12)
    },
    {
      slug: "comoros-ii",
      num: "12",
      featured: true,
      title: "Comoros II",
      location: "Abidjan, Côte d'Ivoire",
      tags: ["Urban", "Urban Design", "2025"],
      typology: "Urban Design",
      year: 2025,
      role: "Architect / Design & Build Oversight",
      status: "Under Construction",
      cost: "$2.5M",
      costNum: 2_500_000,
      client: "MB Holdings / Westford International",
      description: "A proposed mixed-use development combining residential apartments and commercial spaces. The design blends coastal tropical architecture with sustainable energy systems, creating a self-sufficient seaside community.",
      cover: covPhoto("comoros-ii"),
      gallery: galFull("comoros-ii", 8),
      photos: phots("comoros-ii", 4)
    },
    {
      slug: "comoros-i",
      num: "21",
      title: "Comoros I",
      location: "Abidjan, Côte d'Ivoire",
      tags: ["Urban", "Mixed-Use", "2024"],
      typology: "Urban Design",
      year: 2024,
      role: "Architect & Co-Promoter",
      status: "Completed",
      cost: "$550,000",
      costNum: 550_000,
      client: "MB Holdings / Westford International",
      description: "The first phase of MB's coastal Abidjan masterplan — a tropical mixed-use cluster pairing residential apartments with ground-floor retail. Established the prototype façade language carried through Comoros II.",
      cover: covPhoto("comoros-i"),
      gallery: galFull("comoros-i", 7),
      photos: phots("comoros-i", 6)
    },
    {
      slug: "life-camp-paradise",
      num: "31",
      featured: true,
      title: "Life Camp Paradise Estate",
      location: "Abuja, Nigeria",
      tags: ["Residential", "Estate", "2024"],
      typology: "Residential",
      year: 2024,
      role: "Architectural Design",
      status: "Completed",
      cost: "$2M",
      costNum: 2_000_000,
      client: "MB Holdings",
      description: "A serene gated mini-estate offering smart, affordable, and eco-friendly homes for Abuja's middle-class professionals — featuring green landscapes and modern communal facilities.",
      cover: covPhoto("life-camp-paradise"),
      gallery: galFull("life-camp-paradise", 7),
      photos: phots("life-camp-paradise", 18)
    },
    {
      slug: "streeterville",
      num: "37",
      title: "Streeterville",
      location: "Abuja, Nigeria",
      tags: ["Residential", "Villas", "2023"],
      typology: "Residential",
      year: 2023,
      role: "Architectural / Urban Development / Construction & Financier",
      status: "Completed",
      cost: "$1M",
      costNum: 1_000_000,
      client: "MB Holdings",
      description: "A luxury residential enclave in Abuja featuring private villas and lifestyle amenities. Designed with a focus on privacy, comfort, and tropical elegance — the development redefines premium living within a secure community.",
      cover: covPhoto("streeterville"),
      gallery: galFull("streeterville", 8),
      photos: phots("streeterville", 4)
    },
    {
      slug: "affordable-housing-africa",
      num: "39",
      title: "Affordable Housing Across Africa",
      location: "Pan-African",
      tags: ["Urban", "Housing", "Research", "2024"],
      typology: "Urban Housing",
      year: 2024,
      role: "Lead Architect & Strategic Investor",
      status: "Under Construction",
      cost: "$25M",
      costNum: 25_000_000,
      client: "MB Holdings",
      description: "A pan-African affordable housing programme rolling out modular, climate-adapted units in partnership with local developers. The programme prioritises material economy, rapid construction, and community-scale planning.",
      cover: covPhoto("affordable-housing-africa"),
      gallery: [],
      photos: phots("affordable-housing-africa", 6)
    },
    {
      slug: "retridol-noun",
      num: "48",
      title: "Retridol Building",
      subtitle: "NOUN",
      location: "Abuja, Nigeria",
      tags: ["Institutional", "Office", "2024"],
      typology: "Institutional",
      year: 2024,
      role: "Lead Architect",
      status: "Under Construction",
      cost: "$750,000",
      costNum: 750_000,
      client: "National Open University of Nigeria",
      description: "A research, training and operational facility for the Research, Training, Innovation, Documentation, Outreach & Linkages (RETRIDOL) directorate of NOUN. Clean, functional and adaptable workspaces meeting international standards.",
      cover: covPhoto("retridol-noun"),
      gallery: galFull("retridol-noun", 5),
      photos: phots("retridol-noun", 13)
    },
    {
      slug: "noun-mccarthy",
      num: "53",
      title: "NOUN McCarthy Study Centre",
      location: "Lagos, Nigeria",
      tags: ["Institutional", "Education", "2024"],
      typology: "Institutional",
      year: 2024,
      role: "Architectural Design",
      status: "Completed",
      cost: "$1.2M",
      costNum: 1_200_000,
      client: "National Open University of Nigeria",
      description: "A satellite study centre for NOUN delivering distance-learning facilities, examination halls and faculty offices. Designed for daylight, passive cooling and minimal maintenance.",
      cover: covPhoto("noun-mccarthy"),
      gallery: galFull("noun-mccarthy", 9),
      photos: phots("noun-mccarthy", 7)
    },
    {
      slug: "st-annes-ibadan",
      num: "58",
      title: "St Annes",
      location: "Ibadan, Oyo State",
      tags: ["Institutional", "Education", "2024"],
      typology: "Institutional",
      year: 2024,
      role: "Architectural Design & Construction",
      status: "Under Construction",
      cost: "$700,000",
      costNum: 700_000,
      client: "St Annes School",
      description: "A learning campus for St Annes Ibadan combining classrooms, administration and assembly spaces. The plan stitches new pavilions into the existing school grounds with shaded courtyards.",
      cover: covPhoto("st-annes-ibadan"),
      gallery: galFull("st-annes-ibadan", 5),
      photos: phots("st-annes-ibadan", 11)
    },
    {
      slug: "noun-faculty-of-law",
      num: "62",
      title: "Faculty of Law",
      subtitle: "NOUN",
      location: "Abuja, Nigeria",
      tags: ["Institutional", "Education", "2024"],
      typology: "Institutional",
      year: 2024,
      role: "Lead Architect",
      status: "Under Construction",
      cost: "$1M",
      costNum: 1_000_000,
      client: "National Open University of Nigeria",
      description: "Faculty of Law building for the National Open University of Nigeria — a teaching, library and moot-court facility designed around quiet study and ceremonial assembly.",
      cover: covPhoto("noun-faculty-of-law"),
      gallery: galFull("noun-faculty-of-law", 10),
      photos: phots("noun-faculty-of-law", 20)
    },
    {
      slug: "private-client-sango-tedo",
      num: "73",
      title: "Private Client",
      subtitle: "Sango-Tedo",
      location: "Sango-Tedo, Lagos",
      tags: ["Residential", "Villa", "2023"],
      typology: "Residential",
      year: 2023,
      role: "Architectural Design",
      status: "Completed",
      cost: "$350,000",
      costNum: 350_000,
      description: "A bespoke private residence on the Lagos lagoon-front mainland, balancing tropical openness with security and privacy.",
      cover: covPhoto("private-client-sango-tedo"),
      gallery: galFull("private-client-sango-tedo", 4),
      photos: phots("private-client-sango-tedo", 3)
    },
    {
      slug: "noun-senate",
      num: "75",
      featured: true,
      title: "NOUN Senate",
      location: "Abuja, Nigeria",
      tags: ["Institutional", "Civic", "2023"],
      typology: "Institutional",
      year: 2023,
      role: "Lead Architect",
      status: "Completed",
      cost: "$1.5M",
      costNum: 1_500_000,
      client: "National Open University of Nigeria",
      description: "Senate Building for the National Open University of Nigeria — a civic-scale academic governance hall with a formal entrance court and ceremonial chambers.",
      cover: covPhoto("noun-senate"),
      gallery: galFull("noun-senate", 20),
      photos: phots("noun-senate", 17)
    },
    {
      slug: "private-client-lekki",
      num: "82",
      title: "Private Client",
      subtitle: "Lekki",
      location: "Nikon Town Estate, Lekki, Lagos",
      tags: ["Residential", "Villa", "2024"],
      typology: "Residential",
      year: 2024,
      role: "Architectural Design",
      status: "Under Construction",
      cost: "$700,000",
      costNum: 700_000,
      description: "A serene private residence located within the prestigious Nikon Town Estate. The design reflects refined minimalism, spatial harmony and intelligent planning — a blend of sophistication and quiet luxury.",
      cover: covPhoto("private-client-lekki"),
      gallery: galFull("private-client-lekki", 3)
    },
    {
      slug: "private-client-ibadan",
      num: "86",
      title: "Private Client",
      subtitle: "Ibadan",
      location: "Ibadan, Oyo State",
      tags: ["Residential", "Villa", "2025"],
      typology: "Residential",
      year: 2025,
      role: "Architectural Design",
      status: "Under Construction",
      cost: "$2.5M",
      costNum: 2_500_000,
      description: "A landmark private villa in Ibadan, drawing on tropical modernist vocabulary — broad eaves, deep verandahs and a strong horizontal datum running through the public spaces.",
      cover: covPhoto("private-client-ibadan"),
      gallery: galFull("private-client-ibadan", 13),
      photos: phots("private-client-ibadan", 9)
    },
    {
      slug: "radisson-hotel",
      num: "91",
      featured: true,
      title: "Radisson Hotel",
      location: "Ibeju-Lekki, Lagos",
      tags: ["Hospitality", "Hotel", "2023"],
      typology: "Hospitality",
      year: 2023,
      role: "Lead Architect / Design Coordination & Co-Promoter",
      status: "Under Construction",
      cost: "$36M",
      costNum: 36_000_000,
      client: "MB Holdings / Radisson Hotel Group",
      description: "An iconic 4-star hotel development situated along the Dangote Refinery corridor. The design merges tropical modernist elements, sustainable systems, and global hospitality standards — a landmark destination redefining coastal luxury.",
      cover: covPhoto("radisson-hotel"),
      gallery: galFull("radisson-hotel", 17),
      photos: phots("radisson-hotel", 11)
    },
    {
      slug: "veritas-kapital-abuja",
      num: "98",
      title: "Veritas Kapital",
      subtitle: "Abuja",
      location: "Abuja, Nigeria",
      tags: ["Commercial", "HQ", "2023"],
      typology: "Commercial",
      year: 2023,
      role: "Architectural Design & Coordination",
      status: "Completed",
      cost: "$1.8M",
      costNum: 1_800_000,
      client: "Veritas Kapital Assurance Plc",
      description: "The corporate headquarters of Veritas Kapital Assurance Plc, designed to communicate transparency, growth, and resilience. The project integrates energy efficiency and elegant façade composition.",
      cover: covPhoto("veritas-kapital-abuja"),
      gallery: galFull("veritas-kapital-abuja", 13),
      photos: phots("veritas-kapital-abuja", 5)
    },
    {
      slug: "veritas-kapital-lagos",
      num: "104",
      title: "Veritas Kapital",
      subtitle: "Lagos",
      location: "Victoria Island, Lagos",
      tags: ["Commercial", "Office", "2023"],
      typology: "Commercial",
      year: 2023,
      role: "Architectural Design & Coordination",
      status: "Completed",
      cost: "$1.8M",
      costNum: 1_800_000,
      client: "Veritas Kapital Assurance Plc",
      description: "A modern regional office designed to enhance productivity and client engagement. The design aesthetic expresses the firm's corporate identity through clean lines, daylight optimisation, and adaptable interiors.",
      cover: covPhoto("veritas-kapital-lagos"),
      gallery: [],
      photos: phots("veritas-kapital-lagos", 3)
    },
    {
      slug: "private-client-ibadan-oyo",
      num: "112",
      title: "Private Client",
      subtitle: "Ibadan, Oyo",
      location: "Ibadan, Oyo State",
      tags: ["Institutional", "Commercial", "Corporate", "2025"],
      typology: "Commercial",
      year: 2025,
      role: "Architectural Design",
      status: "Under Construction",
      cost: "$2.5M",
      costNum: 2_500_000,
      description: "An institutional office and training facility designed to international standards — clean, functional and adaptable workspaces with a generous double-height arrival.",
      cover: covPhoto("private-client-ibadan-oyo"),
      gallery: galFull("private-client-ibadan-oyo", 13),
      photos: phots("private-client-ibadan-oyo", 14)
    },
    {
      slug: "belvedere-terrace-1",
      num: "118",
      title: "Belvedere Terrace I",
      location: "Lagos, Nigeria",
      tags: ["Residential", "Terrace", "2018"],
      typology: "Residential",
      year: 2018,
      role: "Architectural Design & Supervision",
      status: "Completed",
      cost: "$1.2M",
      costNum: 1_200_000,
      description: "A refined residential community emphasising architectural harmony, green spaces, and family-oriented living. Sustainable materials and elegant landscaping define the estate's calm, contemporary feel.",
      cover: covPhoto("belvedere-terrace-1"),
      gallery: galFull("belvedere-terrace-1", 6),
      photos: phots("belvedere-terrace-1", 3)
    },
    {
      slug: "belvedere-terrace-2",
      num: "121",
      title: "Belvedere Terrace II",
      location: "Lagos, Nigeria",
      tags: ["Residential", "Terrace", "2018"],
      typology: "Residential",
      year: 2018,
      role: "Architectural Design & Supervision",
      status: "Completed",
      cost: "$2.1M",
      costNum: 2_100_000,
      description: "The second phase of the Belvedere community — adding a denser cluster of terrace homes, a shared green spine and a pavilion for residents.",
      cover: covPhoto("belvedere-terrace-2"),
      gallery: [],
      photos: phots("belvedere-terrace-2", 3)
    },
    {
      slug: "private-client-villa",
      num: "128",
      title: "Private Client Villa",
      location: "Ibadan, Oyo State",
      tags: ["Residential", "Villa", "Construction", "2025"],
      typology: "Residential",
      year: 2025,
      role: "Architectural Design / Construction",
      status: "Completed",
      cost: "$7M",
      costNum: 7_000_000,
      description: "A bespoke private villa balancing privacy and entertainment: a quiet family wing offset against a generous public hall opening onto landscaped grounds.",
      cover: ""
    },
    {
      slug: "hotel-surulere",
      num: "133",
      title: "Hotel Development",
      subtitle: "Surulere",
      location: "Surulere, Lagos",
      tags: ["Hospitality", "Hotel", "2023"],
      typology: "Hospitality",
      year: 2023,
      role: "Architectural Design",
      status: "Completed",
      cost: "$1.5M",
      costNum: 1_500_000,
      description: "A boutique hotel development in mainland Lagos — compact site, double-loaded rooms, rooftop bar, and a discreet street arrival.",
      cover: covPhoto("hotel-surulere"),
      gallery: galFull("hotel-surulere", 22),
      photos: phots("hotel-surulere", 20)
    },
    {
      slug: "rccg-goshen",
      num: "138",
      title: "RCCG Goshen Parish",
      location: "Lagos, Nigeria",
      tags: ["Institutional", "Worship", "2024"],
      typology: "Institutional",
      year: 2024,
      role: "Architectural Design",
      status: "Completed",
      cost: "$800,000",
      costNum: 800_000,
      client: "Redeemed Christian Church of God",
      description: "A 1,200-seat worship auditorium with ancillary classrooms, offices and a children's wing — all wrapped in a calm, daylit envelope.",
      cover: covPhoto("rccg-goshen"),
      gallery: galFull("rccg-goshen", 7),
      photos: phots("rccg-goshen", 4)
    },
    {
      slug: "b12-airport-road",
      num: "144",
      title: "B12 Airport Road",
      location: "Ikeja, Lagos",
      tags: ["Residential", "Apartments", "Construction", "2024"],
      typology: "Residential",
      year: 2024,
      role: "Lead Architect & Investor",
      status: "Completed",
      cost: "$650,000",
      costNum: 650_000,
      client: "MB Holdings — EPMB",
      description: "A compact apartment block on Lagos's airport corridor — efficient unit planning, secure parking podium, and a rooftop terrace with skyline views.",
      cover: covPhoto("b12-airport-road"),
      gallery: galFull("b12-airport-road", 3)
    },
    {
      slug: "hotel-288-ilorin",
      num: "151",
      title: "Hotel 288",
      subtitle: "University of Ilorin",
      location: "Ilorin, Kwara State",
      tags: ["Hospitality", "Campus Hotel", "2024"],
      typology: "Hospitality",
      year: 2024,
      role: "Architectural Design",
      status: "Completed",
      cost: "$300,000",
      costNum: 300_000,
      description: "A 288-key campus hotel for the University of Ilorin — accommodating visiting academics, conferences and alumni events.",
      cover: covPhoto("hotel-288-ilorin"),
      gallery: galFull("hotel-288-ilorin", 4),
      photos: phots("hotel-288-ilorin", 3)
    },
    {
      slug: "noun-villa-staff",
      num: "157",
      title: "Staff Quarters",
      subtitle: "NOUN",
      location: "Abuja, Nigeria",
      tags: ["Residential", "Construction", "2024"],
      typology: "Residential",
      year: 2024,
      role: "Architectural Design",
      status: "Completed",
      cost: "$80,000",
      costNum: 80_000,
      client: "National Open University of Nigeria",
      description: "Staff quarters built to the NOUN's institutional standard — repeatable units across a landscaped courtyard.",
      cover: ""
    },
    {
      slug: "veritas-branch-network",
      num: "162",
      title: "Veritas Branch Network",
      location: "Multi-city, Nigeria",
      tags: ["Commercial", "Retail", "2024"],
      typology: "Commercial",
      year: 2024,
      role: "Architectural Design & Roll-Out",
      status: "Completed",
      cost: "$500,000",
      costNum: 500_000,
      client: "Veritas Kapital Assurance Plc",
      description: "A rollout of contemporary insurance branches designed to balance brand visibility, customer experience and operational efficiency.",
      cover: ""
    },
    {
      slug: "ikate-residential",
      num: "166",
      title: "Ikate Residential",
      location: "Ikate, Lagos",
      tags: ["Residential", "Multi-family", "2018"],
      typology: "Residential",
      year: 2018,
      role: "Architectural Design",
      status: "Concept Stage",
      cost: "$2M",
      costNum: 2_000_000,
      description: "A large-scale residential development designed to deliver high-density urban living within Ikate, Lagos. The scheme prioritises efficient unit planning, structured parking and landscaped courtyards.",
      cover: covPhoto("ikate-residential"),
      gallery: galFull("ikate-residential", 7),
      photos: phots("ikate-residential", 3)
    },
    {
      slug: "terrace-apartment-anthony",
      num: "171",
      title: "Terrace Apartment",
      subtitle: "Anthony",
      location: "Anthony, Lagos",
      tags: ["Residential", "Apartments", "2024"],
      typology: "Residential",
      year: 2024,
      role: "Architectural Design / Construction",
      status: "Concept Stage",
      cost: "$2M",
      costNum: 2_000_000,
      description: "A boutique terrace-apartment scheme for the Anthony neighbourhood — three storeys of duplex units around a private courtyard.",
      cover: covPhoto("terrace-apartment-anthony"),
      gallery: galFull("terrace-apartment-anthony", 6),
      photos: phots("terrace-apartment-anthony", 5)
    },
    {
      slug: "private-client-anthony",
      num: "176",
      title: "Private Client",
      subtitle: "Anthony",
      location: "Anthony, Lagos",
      tags: ["Residential", "Villa", "Construction", "2024"],
      typology: "Residential",
      year: 2024,
      role: "Architectural Design / Construction",
      status: "Under Construction",
      cost: "$1M",
      costNum: 1_000_000,
      description: "A modern family villa, planned across two split levels with a sunken family room and a generous landscaped garden.",
      cover: ""
    },
    {
      slug: "private-client-ikoyi",
      num: "181",
      title: "Private Client",
      subtitle: "Ikoyi",
      location: "Ikoyi, Lagos",
      tags: ["Residential", "Villa", "2023"],
      typology: "Residential",
      year: 2023,
      role: "Architectural Design",
      status: "Concept Stage",
      cost: "$600,000",
      costNum: 600_000,
      description: "A private residence on a leafy Ikoyi street, organised around a courtyard pool and shaded loggia.",
      cover: ""
    },
    {
      slug: "country-home",
      num: "187",
      title: "Country Home",
      location: "Oyo State",
      tags: ["Residential", "Country Home", "Construction", "2020"],
      typology: "Residential",
      year: 2020,
      role: "Architectural Design / Construction",
      status: "Completed",
      cost: "$100,000",
      costNum: 100_000,
      description: "A weekend country home — pavilion plan, deep verandahs, planted around mature shade trees.",
      cover: covPhoto("country-home"),
      gallery: galFull("country-home", 15),
      photos: phots("country-home", 6)
    },
    {
      slug: "private-client-suburban",
      num: "192",
      title: "Private Client",
      subtitle: "Suburban",
      location: "Lagos, Nigeria",
      tags: ["Residential", "Villa", "2022"],
      typology: "Residential",
      year: 2022,
      role: "Architectural Design",
      status: "Completed",
      cost: "$120,000",
      costNum: 120_000,
      description: "A compact suburban family home — a tight street footprint opening into a generous rear garden.",
      cover: ""
    },
    {
      slug: "bank-branch-rollout",
      num: "197",
      title: "Bank Branch Rollout",
      location: "Multi-city, Nigeria",
      tags: ["Commercial", "Retail Banking", "2024"],
      typology: "Commercial",
      year: 2024,
      role: "Architectural Design & Roll-Out",
      status: "Completed",
      cost: "$60k–$120k per branch",
      costNum: 90_000,
      description: "A rollout of contemporary bank branches designed to balance brand visibility, customer experience, and operational efficiency. The architecture delivers a recognisable identity while flexing across site geometries.",
      cover: ""
    },
    {
      slug: "branded-banking-prototype",
      num: "203",
      title: "Branded Banking Prototype",
      location: "Lagos, Nigeria",
      tags: ["Commercial", "Retail Banking", "2023"],
      typology: "Commercial",
      year: 2023,
      role: "Architectural Design",
      status: "Completed",
      cost: "$60k–$120k",
      costNum: 90_000,
      description: "A modular banking-branch prototype — a kit-of-parts façade, signage and interior fitout that can be deployed across new and existing buildings.",
      cover: ""
    },
    {
      slug: "regional-office-development",
      num: "208",
      title: "Regional Office Development",
      location: "Lagos, Nigeria",
      tags: ["Commercial", "Office", "2023"],
      typology: "Commercial",
      year: 2023,
      role: "Architectural Design",
      status: "Completed",
      cost: "$500,000",
      costNum: 500_000,
      description: "A regional office building delivered for an international client — five storeys of flexible, daylit floor plates over a basement parking podium.",
      cover: ""
    },
    {
      slug: "event-center-agidingbi",
      num: "213",
      title: "Event Center",
      subtitle: "Agidingbi",
      location: "Agidingbi, Lagos",
      tags: ["Hospitality", "Events", "2024"],
      typology: "Hospitality",
      year: 2024,
      role: "Architectural Design",
      status: "Concept Stage",
      cost: "$250,000",
      costNum: 250_000,
      description: "A multipurpose event center tailored for conferences, weddings and cultural functions. The open-span halls, modular lighting and generous parking define a new benchmark for hospitality in mainland Lagos.",
      cover: covPhoto("event-center-agidingbi"),
      gallery: galFull("event-center-agidingbi", 3),
      photos: phots("event-center-agidingbi", 3)
    },
    {
      slug: "boutique-hotel-mainland",
      num: "218",
      title: "Boutique Hotel",
      subtitle: "Mainland",
      location: "Lagos Mainland",
      tags: ["Hospitality", "Boutique", "2024"],
      typology: "Hospitality",
      year: 2024,
      role: "Architectural Design",
      status: "Concept Stage",
      cost: "$500,000",
      costNum: 500_000,
      description: "A boutique 36-key hotel — a vertical hospitality stack with a ground-floor café, mezzanine co-working and a rooftop bar.",
      cover: covPhoto("boutique-hotel-mainland"),
      gallery: galFull("boutique-hotel-mainland", 6),
      photos: phots("boutique-hotel-mainland", 4)
    },
    {
      slug: "residential-development-surulere",
      num: "224",
      title: "Residential Development",
      subtitle: "Surulere",
      location: "Surulere, Lagos",
      tags: ["Residential", "Apartments", "2018"],
      typology: "Residential",
      year: 2018,
      role: "Architectural Design",
      status: "Concept Stage",
      cost: "$4M",
      costNum: 4_000_000,
      description: "A residential development for the Surulere mainland — three connected blocks above a parking podium, a shared landscaped deck and a community pool.",
      cover: covPhoto("residential-development-surulere"),
      gallery: galFull("residential-development-surulere", 3),
      photos: phots("residential-development-surulere", 4)
    },
    {
      slug: "affordable-estate-scheme",
      num: "230",
      title: "Affordable Estate Scheme",
      location: "Lagos, Nigeria",
      tags: ["Residential", "Affordable", "Estate", "2024"],
      typology: "Urban Housing",
      year: 2024,
      role: "Architectural Design",
      status: "Concept Stage",
      cost: "$1M",
      costNum: 1_000_000,
      description: "A pilot affordable-housing estate — a phased rollout of one- and two-bedroom units across a strict, repeatable site grid.",
      cover: covPhoto("affordable-estate-scheme"),
      gallery: galFull("affordable-estate-scheme", 6),
      photos: phots("affordable-estate-scheme", 6)
    },
    {
      slug: "block-of-flats-surulere",
      num: "237",
      title: "Block of Flats",
      subtitle: "Surulere",
      location: "Surulere, Lagos",
      tags: ["Residential", "Apartments", "2024"],
      typology: "Residential",
      year: 2024,
      role: "Architectural Design",
      status: "Completed",
      cost: "On Request",
      description: "A 12-unit apartment block on a tight Surulere infill site — generous balconies, naturally cross-ventilated apartments, and a small ground-level community room.",
      cover: covPhoto("block-of-flats-surulere"),
      gallery: galFull("block-of-flats-surulere", 4),
      photos: phots("block-of-flats-surulere", 4)
    },
    {
      slug: "terrace-apartment-lekki",
      num: "243",
      title: "Terrace Apartment",
      subtitle: "Lekki",
      location: "Lekki, Lagos",
      tags: ["Residential", "Construction", "Financier", "2024"],
      typology: "Residential",
      year: 2024,
      role: "Construction & Financier",
      status: "Completed",
      cost: "On Request",
      description: "A boutique terrace-apartment build on the Lekki corridor, delivered as a turnkey design-build-finance package.",
      cover: covPhoto("terrace-apartment-lekki"),
      gallery: galFull("terrace-apartment-lekki", 4),
      photos: phots("terrace-apartment-lekki", 4)
    },
    {
      slug: "elevation-church-lekki",
      num: "249",
      title: "Elevation Church",
      location: "Lekki, Lagos",
      tags: ["Institutional", "Worship", "2025"],
      typology: "Institutional",
      year: 2025,
      role: "Architectural Design",
      status: "Concept Stage",
      cost: "On Request",
      description: "A contemporary worship campus on the Lekki peninsula — a dramatic 2,500-seat auditorium, kids' wing, and a flexible plaza for community events.",
      cover: covPhoto("elevation-church-lekki"),
      gallery: galFull("elevation-church-lekki", 2),
      photos: phots("elevation-church-lekki", 3)
    },
    {
      slug: "lekki-villa-cluster",
      num: "256",
      title: "Lekki Villa Cluster",
      location: "Lekki, Lagos",
      tags: ["Residential", "Construction", "2025"],
      typology: "Residential",
      year: 2025,
      role: "Construction",
      status: "Concept Stage",
      description: "A small cluster of detached villas on a gated Lekki estate — each unit individually planned but unified by a shared material palette and roofline.",
      cover: ""
    },
    {
      slug: "abuja-villa-2025",
      num: "262",
      title: "Abuja Villa",
      location: "Abuja, Nigeria",
      tags: ["Residential", "Construction", "2025"],
      typology: "Residential",
      year: 2025,
      role: "Construction",
      status: "Concept Stage",
      description: "A statement family villa in Abuja's quiet diplomatic district, organised around a north-facing entry court and a pool terrace to the south.",
      cover: ""
    },
    {
      slug: "ibadan-villa-2025",
      num: "267",
      title: "Ibadan Villa",
      location: "Ibadan, Oyo State",
      tags: ["Residential", "Construction", "2025"],
      typology: "Residential",
      year: 2025,
      role: "Construction",
      status: "Concept Stage",
      description: "A modern Ibadan villa drawing on local masonry traditions — laterite walls, deep arcades and a generous, climate-tuned living core.",
      cover: ""
    },
    {
      slug: "noun-mccarthy-lagos",
      num: "273",
      title: "NOUN McCarthy Centre",
      location: "Lagos, Nigeria",
      tags: ["Institutional", "Education", "2024"],
      typology: "Institutional",
      year: 2024,
      role: "Architectural Design",
      status: "Completed",
      description: "Study centre for NOUN's Lagos catchment — examination halls, faculty rooms and a public library wing.",
      cover: ""
    },
    {
      slug: "urban-housing-2025",
      num: "279",
      title: "Urban Housing 2025",
      location: "Lagos, Nigeria",
      tags: ["Residential", "Urban Development", "Architectural Design", "Financier", "2025"],
      typology: "Urban Housing",
      year: 2025,
      role: "Architectural Design / Urban Development / Financier",
      status: "Concept Stage",
      description: "A flagship urban-housing scheme for 2025 — combining MB's design office with the in-house financing arm of MB Holdings.",
      cover: ""
    },
    {
      slug: "residential-urban-development-2025",
      num: "284",
      title: "Mixed-Use Block",
      location: "Lagos, Nigeria",
      tags: ["Residential", "Urban Development", "Construction", "Financier", "2025"],
      typology: "Urban Design",
      year: 2025,
      role: "Architectural / Urban Development / Construction & Financier",
      status: "Concept Stage",
      description: "A mid-rise mixed-use block with retail at grade, co-working on the mezzanine and rental apartments above.",
      cover: ""
    },
    {
      slug: "infill-housing",
      num: "289",
      title: "Infill Housing",
      location: "Lagos, Nigeria",
      tags: ["Residential", "Urban Development", "Construction", "Financier", "2025"],
      typology: "Urban Housing",
      year: 2025,
      role: "Architectural / Urban Development / Construction & Financier",
      status: "Concept Stage",
      description: "An infill housing typology designed for under-utilised mainland Lagos plots — a repeatable kit that adapts to varying widths and frontages.",
      cover: ""
    },
    {
      slug: "mb-holdings-hq",
      num: "295",
      title: "MB Holdings Head Office",
      location: "Yaba, Lagos",
      tags: ["Commercial", "HQ", "2025"],
      typology: "Commercial",
      year: 2025,
      role: "Architectural Design",
      status: "Under Construction",
      cost: "$1.5M",
      costNum: 1_500_000,
      client: "MB Holdings",
      description: "Headquarters for MB Holdings on Lagos's Yaba mainland — a quiet, dignified workplace that signals the group's evolution from architectural studio to integrated developer.",
      cover: covPhoto("mb-holdings-hq"),
      gallery: galFull("mb-holdings-hq", 1)
    },
    {
      slug: "mb-architects-hq",
      num: "299",
      title: "MB Architects HQ",
      location: "Yaba, Lagos",
      tags: ["Commercial", "Studio", "2025"],
      typology: "Commercial",
      year: 2025,
      role: "Architectural Design",
      status: "Under Construction",
      description: "MB Architects' own studio building — a working prototype for the firm's design philosophy, with open studios, a model-making shop and a public exhibition gallery at street level.",
      cover: ""
    },
    {
      slug: "research-eko-atlantic",
      num: "303",
      title: "Eco-Friendly Materials Study",
      subtitle: "Eko Atlantic",
      location: "Eko Atlantic City, V/I, Lagos",
      tags: ["Research", "Sustainability", "2024"],
      typology: "Research",
      year: 2024,
      role: "Principal Researcher",
      status: "Published",
      description: "An assessment of eco-friendly building materials applied to the National Christian Centre in Eko Atlantic City — evaluating embodied carbon, durability under coastal exposure, and lifecycle cost.",
      cover: ""
    },
    {
      slug: "research-ibeju-lekki",
      num: "307",
      title: "Eco-Friendly Materials Study",
      subtitle: "Ibeju-Lekki",
      location: "Ibeju-Lekki, Lagos",
      tags: ["Research", "Sustainability", "2025"],
      typology: "Research",
      year: 2025,
      role: "Principal Researcher",
      status: "Published",
      description: "Evaluation of sustainable building materials in selected houses towards the design of an eco-friendly estate in Ibeju-Lekki — exploring whether sustainable materials can reduce environmental impact while improving energy efficiency, housing quality, and long-term affordability.",
      cover: ""
    },

    /* ── 20 NEW ENTRIES (backed by portfolio image folders) ── */
    {
      slug: "5-units-detached",
      num: "310",
      title: "5-Units Detached Development",
      subtitle: "Lekki",
      location: "Lekki, Lagos State",
      tags: ["Residential", "Detached", "2024"],
      typology: "Residential",
      year: 2024,
      role: "Architectural Design",
      status: "Under Construction",
      cost: "$1M",
      costNum: 1_000_000,
      description: "Five detached residential units arranged around shared access and landscaped spaces, balancing privacy with a sense of community.",
      cover: covPhoto("5-units-detached"),
      gallery: galFull("5-units-detached", 12),
      photos: phots("5-units-detached", 7)
    },
    {
      slug: "affordable-housing",
      num: "315",
      title: "Affordable Housing",
      location: "Nigeria",
      tags: ["Urban Housing", "Affordable", "2024"],
      typology: "Urban Housing",
      year: 2024,
      role: "Architectural Design",
      status: "Concept Stage",
      cost: "On Request",
      description: "Affordable housing prototype emphasising material economy, rapid construction and community-scale planning for Nigerian cities.",
      cover: covPhoto("affordable-housing"),
      gallery: galFull("affordable-housing", 10),
      photos: phots("affordable-housing", 7)
    },
    {
      slug: "centre-of-excellence-funaab",
      num: "320",
      title: "Centre of Excellence",
      subtitle: "FUNAAB",
      location: "Ogun State, Nigeria",
      tags: ["Institutional", "Research", "2024"],
      typology: "Institutional",
      year: 2024,
      role: "Architectural Design",
      status: "Concept Stage",
      cost: "$12M",
      costNum: 12_000_000,
      client: "Federal University of Agriculture, Abeokuta",
      description: "A world-class academic and research facility promoting agricultural innovation at the Federal University of Agriculture, Abeokuta.",
      cover: covPhoto("centre-of-excellence-funaab"),
      gallery: galFull("centre-of-excellence-funaab", 15),
      photos: phots("centre-of-excellence-funaab", 14)
    },
    {
      slug: "crestview-radiology",
      num: "325",
      title: "CrestView Radiology Centre",
      location: "Lagos State, Nigeria",
      tags: ["Institutional", "Healthcare", "2023"],
      typology: "Institutional",
      year: 2023,
      role: "Architectural Design",
      status: "Completed",
      cost: "$100,000",
      costNum: 100_000,
      description: "A specialist healthcare facility prioritising diagnostic efficiency, patient comfort and controlled circulation.",
      cover: covPhoto("crestview-radiology"),
      gallery: galFull("crestview-radiology", 2)
    },
    {
      slug: "faculty-earth-science-babcock",
      num: "330",
      title: "Faculty of Earth & Environmental Science",
      subtitle: "Babcock University",
      location: "Ogun State, Nigeria",
      tags: ["Institutional", "Education", "2024"],
      typology: "Institutional",
      year: 2024,
      role: "Architectural Design",
      status: "Concept Stage",
      cost: "$1M",
      costNum: 1_000_000,
      client: "Babcock University",
      description: "An academic faculty with landscaped courtyards, shaded walkways and climate-responsive façades.",
      cover: covPhoto("faculty-earth-science-babcock"),
      gallery: galFull("faculty-earth-science-babcock", 4),
      photos: phots("faculty-earth-science-babcock", 3)
    },
    {
      slug: "heritage-bank",
      num: "335",
      title: "Heritage Bank",
      subtitle: "Branch Network",
      location: "Lagos State, Nigeria",
      tags: ["Commercial", "Retail Banking", "2023"],
      typology: "Commercial",
      year: 2023,
      role: "Architectural Design & Roll-Out",
      status: "Completed",
      cost: "$60k–$120k per branch",
      costNum: 90_000,
      client: "Heritage Bank",
      description: "Rollout of contemporary Heritage Bank branches balancing brand identity with varying site conditions across Lagos.",
      cover: covPhoto("heritage-bank"),
      gallery: galFull("heritage-bank", 15),
      photos: phots("heritage-bank", 11)
    },
    {
      slug: "lagos-state-secondary-school",
      num: "340",
      title: "Lagos State Secondary School",
      location: "Lagos State, Nigeria",
      tags: ["Institutional", "Education", "2023"],
      typology: "Institutional",
      year: 2023,
      role: "Architectural Design",
      status: "Concept Stage",
      cost: "$900,000",
      costNum: 900_000,
      client: "Lagos State Government",
      description: "A modern public secondary school delivering adaptable classrooms and communal areas for Lagos State students.",
      cover: covPhoto("lagos-state-secondary-school"),
      gallery: galFull("lagos-state-secondary-school", 13),
      photos: phots("lagos-state-secondary-school", 11)
    },
    {
      slug: "lekki-hotel",
      num: "345",
      title: "Lekki Hotel",
      location: "Lekki, Lagos State",
      tags: ["Hospitality", "Hotel", "2024"],
      typology: "Hospitality",
      year: 2024,
      role: "Architectural Design",
      status: "Under Construction",
      cost: "$1M",
      costNum: 1_000_000,
      description: "A mid-scale hospitality development serving business and leisure travellers on the Lekki corridor.",
      cover: covPhoto("lekki-hotel"),
      gallery: galFull("lekki-hotel", 11),
      photos: phots("lekki-hotel", 6)
    },
    {
      slug: "mountain-top-hostel",
      num: "350",
      title: "Mountain Top University Hostel",
      location: "Ogun State, Nigeria",
      tags: ["Institutional", "Hostel", "2023"],
      typology: "Institutional",
      year: 2023,
      role: "Architectural Design",
      status: "Concept Stage",
      cost: "$600,000",
      costNum: 600_000,
      client: "Mountain Top University",
      description: "A purpose-designed student hostel with efficient room planning and durable materials.",
      cover: covPhoto("mountain-top-hostel"),
      gallery: galFull("mountain-top-hostel", 3)
    },
    {
      slug: "nicc-building",
      num: "355",
      title: "NICC Building",
      subtitle: "NOUN",
      location: "Abuja, Nigeria",
      tags: ["Institutional", "Mixed-Use", "2023"],
      typology: "Institutional",
      year: 2023,
      role: "Architectural Design",
      status: "Completed",
      cost: "$185,000",
      costNum: 185_000,
      client: "National Open University of Nigeria",
      description: "A modern institutional development for NOUN integrating offices, event spaces and retail.",
      cover: covPhoto("nicc-building"),
      gallery: galFull("nicc-building", 5),
      photos: phots("nicc-building", 3)
    },
    {
      slug: "office-development-cmd-1",
      num: "360",
      title: "Office Development CMD Road",
      subtitle: "Magodo — Phase 1",
      location: "Magodo, Lagos State",
      tags: ["Commercial", "Office", "2023"],
      typology: "Commercial",
      year: 2023,
      role: "Architectural Design",
      status: "Concept Stage",
      cost: "$500,000",
      costNum: 500_000,
      description: "A contemporary mid-rise office along CMD Road with flexible floor plates and a strong urban presence.",
      cover: covPhoto("office-development-cmd-1"),
      gallery: galFull("office-development-cmd-1", 1),
      photos: phots("office-development-cmd-1", 3)
    },
    {
      slug: "office-development-cmd-2",
      num: "365",
      title: "Office Development CMD Road",
      subtitle: "Magodo — Phase 2",
      location: "Magodo, Lagos State",
      tags: ["Commercial", "Office", "2024"],
      typology: "Commercial",
      year: 2024,
      role: "Architectural Design",
      status: "Completed",
      cost: "$250,000",
      costNum: 250_000,
      description: "Completed flexible workspace with natural lighting and contemporary finishes — Phase 2 of the CMD Road development.",
      cover: covPhoto("office-development-cmd-2"),
      gallery: galFull("office-development-cmd-2", 2),
      photos: phots("office-development-cmd-2", 3)
    },
    {
      slug: "onasanya-development",
      num: "370",
      title: "Onasanya Development",
      subtitle: "Surulere",
      location: "Surulere, Lagos State",
      tags: ["Residential", "Apartments", "2024"],
      typology: "Residential",
      year: 2024,
      role: "Architectural Design",
      status: "Under Construction",
      cost: "$600,000",
      costNum: 600_000,
      description: "A purpose-built block of apartments designed for efficiency, sustainability and a clear corporate identity.",
      cover: covPhoto("onasanya-development"),
      gallery: galFull("onasanya-development", 5),
      photos: phots("onasanya-development", 6)
    },
    {
      slug: "private-client-bayelsa",
      num: "375",
      title: "Private Client",
      subtitle: "Bayelsa",
      location: "Bayelsa State, Nigeria",
      tags: ["Residential", "Villa", "2023"],
      typology: "Residential",
      year: 2023,
      role: "Architectural Design",
      status: "Completed",
      cost: "$80,000",
      costNum: 80_000,
      description: "A modest private residence prioritising cost-efficiency, functionality and climatic responsiveness.",
      cover: covPhoto("private-client-bayelsa"),
      gallery: galFull("private-client-bayelsa", 5),
      photos: phots("private-client-bayelsa", 3)
    },
    {
      slug: "private-client-home-library",
      num: "380",
      title: "Private Client",
      subtitle: "Home Library, Lagos",
      location: "Lagos State, Nigeria",
      tags: ["Residential", "Villa", "2024"],
      typology: "Residential",
      year: 2024,
      role: "Architectural Design",
      status: "Completed",
      cost: "$120,000",
      costNum: 120_000,
      description: "A luxury private residence with expansive glazing, double-volume living and African modernist detailing — anchored by a private home library.",
      cover: covPhoto("private-client-home-library"),
      gallery: galFull("private-client-home-library", 5),
      photos: phots("private-client-home-library", 3)
    },
    {
      slug: "private-client-office-dev",
      num: "385",
      title: "Private Client Office Development",
      location: "Lagos State, Nigeria",
      tags: ["Commercial", "Office", "2023"],
      typology: "Commercial",
      year: 2023,
      role: "Architectural Design",
      status: "Completed",
      cost: "$500,000",
      costNum: 500_000,
      description: "Multi-tenant commercial offices delivering compact, efficient spaces for investment-grade use.",
      cover: covPhoto("private-client-office-dev"),
      gallery: galFull("private-client-office-dev", 2)
    },
    {
      slug: "private-client-ogun",
      num: "390",
      title: "Private Client",
      subtitle: "Ogun Country Home",
      location: "Ogun State, Nigeria",
      tags: ["Residential", "Country Home", "2023"],
      typology: "Residential",
      year: 2023,
      role: "Architectural Design",
      status: "Completed",
      cost: "$100,000",
      costNum: 100_000,
      description: "A bespoke country retreat blending traditional proportions with modern detailing.",
      cover: covPhoto("private-client-ogun"),
      gallery: galFull("private-client-ogun", 4),
      photos: phots("private-client-ogun", 3)
    },
    {
      slug: "summerwood-villa",
      num: "395",
      title: "Summerwoods Villa",
      location: "Lagos State, Nigeria",
      tags: ["Residential", "Villa", "2023"],
      typology: "Residential",
      year: 2023,
      role: "Architectural Design",
      status: "Completed",
      cost: "$500,000",
      costNum: 500_000,
      description: "A contemporary urban villa with clean lines, generous glazing and refined private living.",
      cover: covPhoto("summerwood-villa"),
      gallery: galFull("summerwood-villa", 5),
      photos: phots("summerwood-villa", 6)
    },
    {
      slug: "twin-tower-ikoyi",
      num: "400",
      title: "Twin Tower Ikoyi",
      location: "Ikoyi, Lagos State",
      tags: ["Commercial", "Mixed-Use", "2024"],
      typology: "Commercial",
      year: 2024,
      role: "Architectural Design",
      status: "Concept Stage",
      cost: "$500,000",
      costNum: 500_000,
      description: "A landmark twin-tower commercial proposal in Ikoyi with shared podium amenities.",
      cover: covPhoto("twin-tower-ikoyi"),
      gallery: galFull("twin-tower-ikoyi", 2),
      photos: phots("twin-tower-ikoyi", 3)
    },
    {
      slug: "unity-bank",
      num: "405",
      title: "Unity Bank",
      subtitle: "Branch Network",
      location: "Multi-city, Nigeria",
      tags: ["Commercial", "Retail Banking", "2023"],
      typology: "Commercial",
      year: 2023,
      role: "Architectural Design & Roll-Out",
      status: "Completed",
      cost: "$60k–$120k per branch",
      costNum: 90_000,
      client: "Unity Bank",
      description: "Unity Bank branch rollout — consistent architectural language adaptable to multiple urban contexts.",
      cover: covPhoto("unity-bank"),
      gallery: galFull("unity-bank", 2),
      photos: phots("unity-bank", 3)
    }
  ];
  return _ALL.filter(p => !UNPUBLISHED.has(p.slug));
})();

window.MB_PROJECT_STATS = (() => {
  const list = window.MB_PROJECTS;
  const sumCost = list.reduce((s, p) => s + (p.costNum || 0), 0);
  const cities = new Set(list.map(p => (p.location || "").split(",").pop().trim()));
  const completed = list.filter(p => /completed|published/i.test(p.status)).length;
  const inProgress = list.filter(p => /under construction|concept/i.test(p.status)).length;
  return {
    count: list.length,
    sumCost,
    cities: cities.size,
    completed,
    inProgress
  };
})();
