name: Publish Website to CPanel
on:
  push:
    branches:
      - main-2.0
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: MBArchitect/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.MB_FTP_SERVER }}
        ftp-username: ${{ secrets.MB_FTP_USERNAME }}
        ftp-password: ${{ secrets.MB_FTP_CONNECT }}
        server-dir: /moyosore-bamigbade.com/


on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.samkirkland.com
        username: myFtpUserName
        password: ${{ secrets.ftp_password }}