on: 
  push:
    branches:
      - main
name: Publish Website to CPanel
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files (MBHoldco)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ${{ secrets.MBH_FTP_SERVER }}
        username: ${{ secrets.MBH_FTP_USERNAME }}
        password: ${{ secrets.MBH_FTP_CONNECT }}
        protocol: ftps
        port: 21

    - name: 📂 Sync files (Moyosore Bamigbade)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ${{ secrets.MB_FTP_SERVER }}
        username: ${{ secrets.MB_FTP_USERNAME }}
        password: ${{ secrets.MB_FTP_CONNECT }}
        protocol: ftps                            # ⬅ important for many cPanel hosts
        port: 21